config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :recipes
  resources :recipe_foods

  post '/add-ingredient', to: "recipes#add_ingredient"
  get '/shopping_list/:recipe_id', to: "recipes#shopping_list"
  get '/foods/new(/:recipe_id)', to: 'foods#new'

  resources :foods
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, Recipe, user_id: user.id
    can :create, Recipe
    can :read, Food
    can :create, Food
    can :destroy, Recipe, user_id: user.id
    can :destroy, Food, user_id: user.id

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :user_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  protect_from_forgery with: :null_session

  # GET /recipes or /recipes.json
  def index
    current_uri = request.env['PATH_INFO']

    @recipes = if current_uri == '/recipes'
                 Recipe.all
               else
                 Recipe.where('public = true').order('created_at DESC')
               end
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @foods = Food.all
    @recipe = Recipe.find(params[:id])
    @recipe_food = RecipeFood.new
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(user: current_user,
                         name: params[:recipe][:name],
                         preparation_time: params[:recipe][:preparation_time],
                         cooking_time: params[:recipe][:cooking_time],
                         description: params[:recipe][:description],
                         public: params[:recipe][:public])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_ingredient
    @food = Food.find(params[:food])
    @recipe = Recipe.find(params[:recipe])
    @recipe_food = RecipeFood.new(food: @food, recipe: @recipe, quantity: params[:recipe_food][:quantity])

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Ingredient was successfully added to recipe.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        @foods = Food.all
        @food_recipe = @recipe.recipe_foods.new
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  def shopping_list
    @shopping_list = Recipe.includes(:recipe_foods).find(params[:recipe_id])
  end

  private

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.fetch(:recipe, {}).permit(:name, :description, :public, :preparation_time, :cooking_time)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? 'bg-gray-900' : ''
  end

  def active_link(link_path)
    current_page?(link_path)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>" class="border-t border-gray-200">
  <dl class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6">
    
      <dt class="text-sm font-medium text-gray-500"><%= food.name %></dt>
      <dd class="mt-1 text-sm text-gray-500"><%= food.measurement_unit %></dd>
      <dd class="mt-1 text-sm text-gray-500"><%= food.price %></dd>
      <dd class="mt-1 text-sm text-gray-500">
        <% if current_user.id == food.user_id %>
        <%= button_to "Destroy this food", food, method: :delete, class: "ml-5 bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 rounded-md shadow-sm text-sm leading-4 px-3 border border-blue-500 hover:border-transparent rounded focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <% end %>
      </dd>
    
  </dl>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food, class: "contents") do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div id='food-form-group' class="md:grid md:grid-cols-3 md:gap-6 py-3.5"%>
    <div>
      <%= form.label :name, style: "display: block", class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :name, class: "focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder:"onion, rice, milk, etc"%>
    </div>

    <div>
      <%= form.label :measurement_unit, style: "display: block", class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :measurement_unit, class: "focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder:"kg, lb, gr, lts, etc" %>
    </div>

    <div>
      <%= form.label :price, style: "display: block", class: "block text-sm font-medium text-gray-700" %>
      <%= form.number_field :price , class: "focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-none rounded-r-md sm:text-sm border-gray-300", placeholder:"$us"%>
    </div>
  </div>

  <div class="inline">
    <%= form.submit class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing food</h1>

  <%= render "form", food: @food %>

  <%= link_to "Show this food", @food, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to foods", foods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/foods/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <% if current_user %>
    <div class="flex justify-end w-5/6 py-10 px-5">
      <!-- <h1 class="font-bold text-4xl ">Foods</h1> -->
      <%= link_to 'Add Food', new_food_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  <% end %>


   <% if @foods.length === 0 %>
    <div id="foods" class="min-w-full">
        <span>No foods found</span>
    </div>
    <% else %>

    <div id="foods" class="min-w-full">
      <dl class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-4 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900"><strong>Name:</strong></dt>
        <dd class="mt-1 text-sm text-gray-900"><strong>Measurement unit:</strong></dd>
        <dd class="mt-1 text-sm text-gray-900"><strong>Price:</strong></dd>
      
          <dd class="mt-1 text-sm text-gray-900"><strong>Action:</strong></dd>
        
      </dl>
      <%= render @foods %>
    </div>
    <% end %>
</div>

app/views/foods/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-center py-0.5">New food</h1>

  <%= render "form", food: @food %>

  <%= link_to 'Back to foods', foods_path, class: "ml-5 bg-white py-2 px-3 border border-gray-300 rounded-md shadow-sm text-sm leading-4 font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
</div>

app/views/foods/show.html.erb
<div class="flex-1 w-32">
  
  <div  class="flex flex-row justify-end">
  <% if user_signed_in? && current_user.id == @food.user_id %>
    <%= link_to "Edit this food", edit_food_path(@food), class: "bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded"  %>
    <% end %>
    <%= link_to "Back to foods", foods_path, class: "ml-5 bg-white py-2 px-3 border border-gray-300 rounded-md shadow-sm text-sm leading-4 font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>
  </div>

  <%= render @food %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <style>
    .dropdown {
      position: relative;
      display: inline-block;
    }

    .dropdown-content {
      display: none;
      position: absolute;
      background-color: #f9f9f9;
      min-width: 160px;
      box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
      z-index: 1;
    }

    .dropdown:hover .dropdown-content {
      display: block;
    }

     /* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 15% auto; /* 15% from the top and centered */
  padding: 20px;
  border: 1px solid #888;
  width: 50%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
} 
    </style>
  <body class="bg-gray-100">
  <!-- This example requires Tailwind CSS v2.0+ -->
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          The Recipe App
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center text-cyan-400">
          <h1><a href="/" class="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium">The Recipe App</a></h1>
        </div>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <% if user_signed_in? %>
              <a href="/recipes" class="<%= active_class('/recipes') %> text-gray-300 hover:bg-cyan-400 hover:text-white px-3 py-2 rounded-md text-sm font-medium">My Recipes</a>
              <a href="/foods" class="<%= active_class('/foods') %> text-gray-300 hover:bg-cyan-400 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Foods</a>
              <div class="dropdown">
              <button id="dropdownDefault" data-dropdown-toggle="dropdown" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-3 py-2 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button"> 
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                </svg> Create  </button>
                <!-- Dropdown menu -->
              <div class="dropdown-content hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700">
                  <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefault">
                    <li>
                      <%= link_to "New recipe", new_recipe_path, class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
                    </li>
                    <li>
                      <%= link_to "New food", new_food_path, class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
                    </li>                  
                  </ul>
              </div>
              </div>
            <% end %>
           
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
      <% unless user_signed_in? %>
        <button type="button" class="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
          <span class="sr-only">View notifications</span>
          <!-- Heroicon name: outline/bell -->
          <%= link_to "Sign in", new_user_session_path, id: 'btn_sign_in', class: "text-gray-300 hover:bg-cyan-400 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
        </button>

        <!-- Profile dropdown -->
        <div class="ml-3 relative">
          <div>
          <%= link_to "Sign up", new_user_registration_path, class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-cyan-400 hover:bg-cyan-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
          </div>
        </div>
         <%end%>
          <% if user_signed_in? %>
          <div class="ml-3 relative">
            <div>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, id: 'btn_sign_out', class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-cyan-400 hover:bg-cyan-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
            </div>
          </div>
          <%end%>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="/" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium" aria-current="page">Home</a>

      <a href="/recipes" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Recipes</a>

      <a href="/foods" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Foods</a>
      <% if user_signed_in? %>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-cyan-400 hover:bg-cyan-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <% end %>
    </div>
  </div>
</nav>
    <main class="mt-28 px-5 flex">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="md:col-span-1">
      <div class="px-4 sm:px-0">
        <h3 class="text-lg font-medium leading-6 text-gray-900">Recipe</h3>
        <p class="mt-1 text-sm text-gray-600">Use the form below to create new recipe information. Please complete all the fields.</p>
      </div>
    </div>
    <div class="mt-5 md:mt-0 md:col-span-2">
      <%= form_with(model: recipe) do |form| %>
        <div class="shadow sm:rounded-md sm:overflow-hidden">
          <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
            <div class="grid grid-cols-3 gap-6">
              <div class="col-span-3 sm:col-span-3">
                <label for="company-website" class="block text-sm font-medium text-gray-700"> Recipe Name </label>
                <div class="mt-1 flex rounded-md shadow-sm">
                <%= form.text_field :name, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded focus:outline-none focus:ring-cyan-500 focus:border-cyan-200 focus:z-10 sm:text-sm", placeholder: 'What would you like to call this recipe' %>
                </div>
              </div>
            </div>
              <div class="grid grid-cols-4 gap-6">
              <div class="col-span-3 sm:col-span-2">
                <label for="company-website" class="block text-sm font-medium text-gray-700"> Preparation Time </label>
                <div class="mt-1 flex rounded-md shadow-sm">
                <%= form.number_field :preparation_time, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded focus:outline-none focus:ring-cyan-500 focus:border-cyan-200 focus:z-10 sm:text-sm", placeholder: 'Please enter a number' %>
                </div>
              </div>
            <div class="col-span-3 sm:col-span-2">
                <label for="company-website" class="block text-sm font-medium text-gray-700"> Cooking time </label>
                <div class="mt-1 flex rounded-md shadow-sm">
                <%= form.number_field :cooking_time, class:"appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded focus:outline-none focus:ring-cyan-500 focus:border-cyan-200 focus:z-10 sm:text-sm", placeholder: 'Please enter a number' %>
                </div>
              </div>
            </div>
            <div>
              <label for="about" class="block text-sm font-medium text-gray-700"> Description </label>
              <div class="mt-1">
                <%= form.text_area :description, rows: 6, class:"shadow-sm focus:ring-cyan-500 focus:border-cyan-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md", placeholder: 'Please provide a full description' %>
              </div>
            </div>
            <div class="col-span-6 sm:col-span-3">
                  <label for="public" class="block text-sm font-medium text-gray-700">Is this recipe public?</label>
                  <select id="public" name="recipe[public]" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-cyan-500 focus:border-cyan-500 sm:text-sm">
                    <option value="true">Yes</option>
                    <option value="false">No</option>
                  </select>
                </div>
          </div>
          <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
            <%= form.submit "Save", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-cyan-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:bg-cyan-200" %>
             <%= link_to "Cancel", recipes_path %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/new.html.erb
<%= render "form", recipe: @recipe %>